FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

COPY needed/pyproject.toml needed/.python-version needed/uv.lock ./
RUN uv sync --locked

COPY Data-ingestion/ingest_data_yellow.py .

ENTRYPOINT ["python", "ingest_data_yellow.py"]